ccflags-y := 	-Wall					\
		-Wextra					\
		-Wno-missing-field-initializers		\
		-Wno-unused-parameter			\
		-Wformat				\
		-O2					\
		-std=gnu18				\
		-g					\
		-Werror=format-security			\
		-Werror=implicit-function-declaration	

lzo_module-y := lzom.o
lzo_module-y += lzo_extend/lzom_compress.o
lzo_module-y += lzo_extend/lzom_decompress_safe.o

obj-m := lzo_module.o